name: pycitizen-ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Label of the container job is 'ci'
  ci:
    # Run on the latest version of an Ubuntu Linux runner hosted by GitHub
    runs-on: ubuntu-latest

    # Service containers to run with 'ci'
    services:
      postgres:
        # Docker Hub image
        image: postgres:9.6.10-alpine
        # Set environment variables
        env:
          POSTGRES_DB: dev
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started by redirecting output
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=pycitizen --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml 
